### ISSUE TITLE
Implement mentor signup questions

### ISSUE THREAD

**Issue by Dalordish** [MelbourneHighSchoolRobotics/RCJA_Registration_System#16]
I'm unsure if we need a terms of service or not, but we should follow this up, and if one is needed/exists, a view for the ToS should be created.

@peter-drew thoughts?

**Comment by peter-drew** [comment]
There are specific requirements for this which I will follow up.


On 31 Dec 2019, at 2:57 am, Richard <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm unsure if we need a terms of service or not, but we should follow this up, and if one is needed/exists, a view for the ToS should be created.

@peter-drew<https://github.com/peter-drew> thoughts?

**Comment by peter-drew** [comment]
Need to create a model that allows a state or national coordinator to create checkbox items that are displayed to mentors dynamically. Need to provide option for mandatory option - eg accepting policy, or optional - eg mailing list.

**Comment by peter-drew** [comment]
Questions will be done on a global scale, modals and backend is now implemented
