### ISSUE TITLE
Links from admin to main site

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#180]

**Comment by Dalordish** [comment]
believe this already exists in the form of "view site" in the top right. can style this to make it more obvious if necessary

**Comment by peter-drew** [comment]
If view_on_site  and  get_absolute_url() are defined then links appear on each model in the admin with links to the main site. Useful for the invoices and events to link to how it appears in the frontend.
