### ISSUE TITLE
Check use of striptags in template is not an xss risk

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#184]
@Dalordish this is probably fine but we should discuss it briefly

**Comment by Dalordish** [comment]
@peter-drew we forgot to talk about this over the phone the other day

**Comment by peter-drew** [comment]
@Dalordish lets (try) and discuss it Thursday

**Comment by peter-drew** [comment]
Not an issue: https://www.djangoproject.com/weblog/2014/mar/22/strip-tags-advisory/

> Note that if you are using the output of strip_tags in a template, or if you are using the striptags template filter, escaping is the default and safe behaviour, unless you have disabled automatic escaping in your templates.
