### ISSUE TITLE
Add first run school administrator notice

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#213]

**Comment by peter-drew** [comment]
@Dalordish What I am thinking is a popup that appears when you go to the edit school page when the following conditions are met:
- Forced redirection to page (test the forceUpdate flag on the school model)
- Popup hasn't already been shown - set a cookie after first shown

Text of popup basically saying, read carefully, please check these details, remove all old admins because they will have access to your school's data. I can do the text if you can do the plumbing.

**Comment by peter-drew** [comment]
This is also pretty important

**Comment by Dalordish** [comment]
I think we should also have a persistent alert banner message for whenever forceUpdate is on explaining why the user is being redirected here.

**Comment by Dalordish** [comment]
@peter-drew  handing over to you for text
