### ISSUE TITLE
Divisions for event not validated

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#25]
Currently mentor view (and probably admin view but not tested) don't restrict the division for a team to divisions available for an event. Dropdown should be filtered to available divisions.

**Comment by Dalordish** [comment]
Can confirm this is broken on admin view too.

**Comment by Dalordish** [comment]
Note that, while in mentor view, you already know the event the team is being created for, and therefore can prepopulate the <options> on the serverside, this is not the case on admin - we'll likely need to write a bit of javascript to make the page dynamically change the options available based on the event selected, **or** modify the admin flow so you have to create a team from within an event

**Comment by peter-drew** [comment]
On admin we could just display them all and throw an error on validation- not hard. Probably won’t ever be too many divisions to be a problem. Otherwise to filter the dropdown would require js.

On 8 Jan 2020, at 12:14 am, Richard <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that, while in mentor view, you already know the event the team is being created for, and therefore can prepopulate the on the serverside, this is not the case on admin - we'll likely need to write a bit of javascript to make the page dynamically change the options available based on the event selected, or modify the admin flow so you have to create a team from within an event
