### ISSUE TITLE
API

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#29]
Needed for both new RCJA website, for displaying available upcoming events and associated information (need to be careful of xss because some html formatting needed) and also for scoring systems integration.

**Comment by peter-drew** [comment]
Basic api added. Need to check permissions before goes into production or remove for now.

**Comment by peter-drew** [comment]
Will just disable for initial release.

**Comment by Dalordish** [comment]
get schema from evan bailey for events api
