### ISSUE TITLE
Admin password change permissions

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#298]

**Comment by Dalordish** [comment]
More detail on what's involved with this card would be good

**Comment by peter-drew** [comment]
Possibly creating a separate permission that gives a coordinator the right to change a user's password, rather than having it coupled with the user_change permission

**Comment by peter-drew** [comment]
This has been largely mitigated by #378: only superusers can edit other superusers and reset their passwords.

**Comment by peter-drew** [comment]
Going to close this, superuser's are already protected and even if such a permission existed, it is unlikely that it would be assigned to anything other than the Full permission level, which already has access.
