### ISSUE TITLE
Add RCJA logo

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#364]
Currently favicon and logo are the placeholder

**Comment by peter-drew** [comment]
This shouldn't be too hard, would be nice to do this - will make the site look more finished

**Comment by evanbailey** [comment]
@peter-drew Zac wil be able to send favicon and logos etc. to you, if you don't have them already.

**Comment by peter-drew** [comment]
> @peter-drew Zac wil be able to send favicon and logos etc. to you, if you don't have them already.

That would be appreciated, the reason it hasn't been done yet is we didn't have the correct sizes and haven't yet created them
