### ISSUE TITLE
User Confusion RE unable to edit teams/students etc. after close date.

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#455]
Zac is getting a few confused users who do not realise that entries have closed and are wonder why they can only view but not edit their entries.

Are we able to add something in so that it is obvious to users if the entries are closed, and that the data is in view only mode, contact the event contact if you need to update?

**Comment by peter-drew** [comment]
There was already text to this effect, but this fix will increase the size from h5 to h1.
