### ISSUE TITLE
How long should the session timeout be?

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#49]
A short session timeout will be annoying for coordinators, but will protect less security conscious mentors who may log in on a shared device.

**Comment by Dalordish** [comment]
The best way to handle it is probably a remember me button, but for now, I think it doesn't really matter, personally I know short session timeouts annoy me a lot and I'd rather have them long - imo most cases of shared computer compromise happen in the immediate hours after login before computer shutdown

**Comment by peter-drew** [comment]
Also need to consider token expiry length for password resets

**Comment by peter-drew** [comment]
Will go middle ground of 2 days for now
