### ISSUE TITLE
Website Display - Workshop Divisions

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#513]
On the website, workshop divisions say 'xxx - Workshop Division'. Should just be xxx.

**Comment by evanbailey** [comment]
I will investigate the JS and confirm.

Evan Bailey | 0467675869 | ***@***.******@***.***>

**Comment by Dalordish** [comment]
If this is the wordpress site we're talking about, this is controlled by:

https://github.com/MelbourneHighSchoolRobotics/RCJA_Website_Source/blob/main/PageContentAutoload.html#L140

```
return acc + `<li> ${division.name} ${division.description ? '- ' + division.description : ''} </li>`
```

Where we display the description of the divisions. For whatever reason, these have been setup wtih the description of: "Workshop Division"

We can either drop this from the site by removing `${division.description ? '- ' + division.description : ''} ` or we can change the descriptions of the divisions on the serverside. Either would work.

**Comment by evanbailey** [comment]
I believe it has that description on the server so we can distinguish between the generic divisions for workshops only (e.g. rescue line) and the normal divisions (e.g. riley rover rescue line).

If we change the JS to not show the description, that would be good. It will be worth making sure what is in your repo for the server matches the website, website could have a few additional changes.

Also noticed another small fix to do, should say 'workshop divisions' if it is a workshop not event divisions. 
![image](https://user-images.githubusercontent.com/28521026/123537617-b7375600-d773-11eb-931e-b8f5da357286.png)

**Comment by evanbailey** [comment]
Nobody has complained about this, better things to worry about.
