### ISSUE TITLE
Team export doesn't have regional flag

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#515]
This will need some discussion

**Comment by evanbailey** [comment]
Scratch the discussion, can just be pulled from the mentor.

**Comment by peter-drew** [comment]
By flag do you just mean include the mentor's region in the team export @evanbailey?

**Comment by evanbailey** [comment]
Yes

Evan Bailey | 0467675869 | ***@***.***


________________________________
