### ISSUE TITLE
Mentor export missing school name

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#516]
Mentor export missing school name

**Comment by peter-drew** [comment]
Because mentors can have multiple schools will need to do a string concatenation.

**Comment by evanbailey** [comment]
Hmmm, we'll need to think about this.

Evan Bailey | 0467675869 | ***@***.***


________________________________

**Comment by peter-drew** [comment]
Concat solution included in #517. Can always improve later.
