### ISSUE TITLE
Workshop support for events

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#52]
This is one of the most important features because registrations for workshops starts before registration for competitions.

May need @Dalordish to help with the frontend, will let you know after I have done the necessary backend changes.

**Comment by Dalordish** [comment]
What distinguishes workshops from competitions/ what details are different?

**Comment by peter-drew** [comment]
No teams, just list of attendees: first & last name, and optionally division. Will do backend and db and see how best to modify frontend. Not main priority at the moment.
