### ISSUE TITLE
Fix create school bug on signup page

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/RCJA_Registration_System#53]

**Comment by Dalordish** [comment]
@peter-drew  you mentioned this broke during the demo - can i get your environment details so i can reproduce to verify if my fix works?

**Comment by peter-drew** [comment]
Was demo heorku, chrome (possibly Edge)

**Comment by Dalordish** [comment]
@peter-drew would you be able to find versions for me if you still have an environment that reproduces? I can't recreate it on my system.

**Comment by peter-drew** [comment]
I’ll have a go at reproducing it.

**Comment by peter-drew** [comment]
I have encountered this bug so am going to close this issue.

**Comment by Dalordish** [comment]
@peter-drew do you mean haven't?

Is possible that demo at the time wasn't up to date with the fix and that would explain it
