### ISSUE TITLE
Invoice showing odd title - (Fix)?

### ISSUE THREAD

**Issue by evanbailey** [MelbourneHighSchoolRobotics/RCJA_Registration_System#532]
![image](https://user-images.githubusercontent.com/28521026/131237402-b34ef8aa-97ad-4ddc-b385-04fb265d4f60.png)

**Comment by peter-drew** [comment]
@evanbailey I think this is because that must have been the name of the event.

**Comment by evanbailey** [comment]
Yes, I expect so.
