### ISSUE TITLE
Add transparency or darkening layer to login bgimage

### ISSUE THREAD

**Issue by Dalordish** [MelbourneHighSchoolRobotics/RCJA_Registration_System#71]
Busy images are visually distracting
Should also change bg colour so that image load does not leave the user with an ugly page while it loads

**Comment by Dalordish** [comment]
Could also do a blur effect, or all three in combination

**Comment by peter-drew** [comment]
@Dalordish is this done?

**Comment by Dalordish** [comment]
Darkening is done, we decided not to add a blur.
